### 1. 댓글 생성
POST http://localhost:8080/api/comments/boards/4b1da82c-f2e5-4778-8be7-4533d5c6390a/comments
Authorization: Bearer jwt_token_string
Content-Type: application/json

{
  "content": "댓글입니다3"
}

###