spring:
  application:
    name: board

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: yeji
    password: 0708
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true

