spring:
  application:
    name: board

  datasource:
    url: jdbc:postgresql://localhost:55432/test
    username: test
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
