spring:
  application:
    name: board

  datasource:
    url: jdbc:postgresql://localhost:5432/board
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: hello12

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

