@postId = 3c275155-6199-417a-8773-a2311b85a183

### CREATE POST
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title" : "test",
  "content" : "test"
}

### UPDATE POST
PUT http://localhost:8080/posts/{{postId}}
Content-Type: application/json

{
  "title" : "test 수정",
  "content" : "test"
}

### DELETE POST
DELETE http://localhost:8080/posts/{{postId}}
Content-Type: application/json

### GET POST DETAILS
GET http://localhost:8080/posts/{{postId}}?page=1&size=15
Content-Type: application/json