### Post CREATE
POST http://localhost:8080/api/posts
Content-Type: application/json

{
    "title": "test title....",
    "content": "test content...."
}

### Get READ
GET http://localhost:8080/api/posts/0df6a3dd-c1db-4689-9335-36985995660e

### Patch UPDATE
PATCH http://localhost:8080/api/posts/cfe8ac2a-1b9a-4400-ae83-8919c49ff8b0
Content-Type: application/json

{
  "title": "update title...."
}

### Delete DELETE
DELETE http://localhost:8080/api/posts/dd7bfd2a-04d6-4ae1-a090-7936b7ffcf66