### Post Create
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "게시글 테스트",
  "content": "게시글 테스트입니다."
}

### Post Patch
PATCH http://localhost:8080/api/posts/d0fd4bc7-ca55-4ab3-8a1a-14f8ad339396
Content-Type: application/json

{
  "title": "게시글 수정 테스트",
  "content": "게시글 수정 테스트입니다."
}

### Post Delete
DELETE http://localhost:8080/api/posts/4d04a59f-6164-44b1-9ec7-b28a182c3216
Content-Type: application/json

### Comment Create
POST http://localhost:8080/api/comments
Content-Type: application/json

{
  "post-id": "df656e48-83f8-46f4-88b4-31b657cee8e9",
  "content": "댓글 테스트 입니다."
}

### Comment Read
GET http://localhost:8080/api/posts/a0d72768-0ca2-40d5-9d25-5f7f194797ea?page=0&size=10&sort=DESC&orderby=CREATED
Content-Type: application/json

### Comment Update
PATCH http://localhost:8080/api/comments/db30789a-d7c7-4e61-be07-d86aa4483bc3
Content-Type: application/json

{
  "post-id": "4ae65aa7-ffa4-4b38-86d2-b333e7accc5a",
  "content": "댓글 수정 테스트입니다."
}

### Comment Delete
DELETE http://localhost:8080/api/comments/1bf18422-16dd-4ad9-be4d-6126ca1e009f
Content-Type: application/json
